#!/bin/bash

: <<COMMENTBLOCK
This script will remove everything from the anat directory that contains "scout", 
for example, sub-th01_scout__dup-023.json.
Following this, the script will call the deface script, and then finally the anat_proc script.
To run this script, please navigate to your BIDS directory, 
for example: /Users/aklovos/Documents/Imaging_Teens_Output/Data/Nifti/Edgin/MDD-IMAGING
Author: Annalysa Lovos created on 4/21/2021
COMMENTBLOCK

if [ $# -lt 1 ]; then
  echo "This script requires one argument (the subject; for example: sub-007joe)"
  echo "The data must be in BIDs format"
  echo "Please navigate to the main BIDS directory."
  echo "for example, cd /Users/aklovos/Documents/Imaging_Teens_Output/Data/Nifti/Edgin/MDD-IMAGING"
  exit 1
fi

subj=${1} 

# Remove all the scout files from the anat directory:
rm ${subj}/anat/${subj}_scout* 
ls ${subj}/anat/

# Call the deface script:
deface ${subj}

# Call anat_proc script:
anat_proc ${subj}

 
